#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts /etc/host.backup
sed -i 'localhost' /etc/hosts
sed -i 'facebook.com' /etc/hosts
echo -e '127.0.0.2     localhost' > /etc/hosts
echo -e '8.8.8.8       facebook.com' >> /etc/hosts
